### ISSUE TITLE
This is perfect for GitHub Pages

### ISSUE THREAD

**Issue by bracketdash** [stinewoodward/hometown-map#8]
See here: https://bracketdash.github.io/hometown-map/

I forked it so I could check it out without downloading anything, but you can totes do the same if you wanted to just send people links to a working copy. It's under the repo's Settings, near the bottom if you're interested. :)

**Comment by stinewoodward** [comment]
One of the assignments in the web map programming class I'm in is working up a portfolio. 

See here: [https://stinewoodward.github.io/](url)

**Comment by bracketdash** [comment]
Ah, very nice! You don't know how happy I am that someone I know from outside the software world is getting into development.

Maybe if you and I both bug Kate about it, she'll let me start teaching her!
